model:
  channels: 3
data:
  root_path: data/stage1_test
  workers: 2
  img_height: 256
  img_width: 256
misc:
  model_path: models/pt-model-dsbowl2018-02-08-202427.pth
  batch_size: 1
  cutoff: 0.5
  viz_masks: true
  make_submission: true
  submission_name: sub-dsb2018-6
